stages:
  - test
  - build
  - deploy

include:
  - local: "homework space/Sample/.gitlab-ci.yml"
  - local: "homework space/Gitlab GCP Runner/.gitlab-ci.yml"
  - local: "desafios/desafio1/Pipeline de Criação e Execução de uma Imagem Docker/.gitlab-ci.yml"
