stages:
  - build
  - deploy

create:
  stage: build
  tags:
    - gcp
  script:
    - cd "desafios/desafio1/Pipeline de Criação e Execução de uma Imagem Docker"
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t williamlimasilva/gcp-runner-challenge-alpha:1.0 app/.
    - docker push williamlimasilva/gcp-runner-challenge-alpha:1.0
    - docker logout

execute:
  stage: deploy
  needs:
    - create
  tags:
    - gcp
  script:
    - docker container stop web-server-alpha || true
    - docker container rm web-server-alpha || true
    - docker run -dti --name web-server-alpha -p 80:80 williamlimasilva/gcp-runner-challenge-alpha:1.0
