FROM node:17-alpine3.14

WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port for the application
EXPOSE 3000

# Start the application
CMD ["npm", "start"]